package com.restController;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.jpa.entity.Book;
import com.jpa.entity.Employee;
import com.jpa.repository.EmployeeRepository;

@RestController
public class EmployeeRestServiceController {
	@Autowired // This means to get the bean called customerRepository, Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepo;
	
	//@CrossOrigin(origins="http://localhost:4020")  -- replace this local setting with global setting
	@GetMapping("/jpaRest/getAllEmp")
	public @ResponseBody Iterable<Employee> getAllEmployees() {
		return employeeRepo.findAll();
	}

	@GetMapping("/jpaRest/getEmpById/{id}")
	public Employee getEmployeeById(@PathVariable Integer id) {
		return employeeRepo.findOne(id);  
	}
}
