package com.restController;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


import com.jpa.entity.Employee;
import com.jpa.repository.EmployeeRepository;

@RestController
public class EmployeeRestServiceController {
	@Autowired // This means to get the bean called customerRepository, Which is auto-generated by Spring, we will use it to handle the data
	private EmployeeRepository employeeRepository;
	

	//@GetMapping(path="/all")
	//@CrossOrigin(origins="http://localhost:4020")  -- replace this local setting with global setting
	@RequestMapping("/employee/all")
	public @ResponseBody Iterable<Employee> getAllEmployees() {
		// This returns a JSON or XML with the users
		return employeeRepository.findAll();
	}
	
}
